topins_list=('tomato','onion','lettuse','pepper','olive')
print(topins_list)
print('select any 3 topins :')
topins1=input('1 topins :')
topins2=input('2 topins :')
topins3=input('3 topins :')
print('you have selected :',topins1.split(','),topins2.split(','),topins3.split(','))
sandwich_required=int(input('total no. of sandwich required :'))
total=(sandwich_required*5)
print('Total Amount :',total,"$")